repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args: [--strict, --ignore-missing-imports]
        files: ^(pyLIDAR/|tests/)
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        files: ^(pyLIDAR/|tests/)
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        include: ^(pyLIDAR/|tests/)
        args: [--settings-path=pyproject.toml]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        files: ^(pyLIDAR/|tests/)
        args: [--max-line-length=88, "--ignore=E203,W503"]
      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade
        language: system
        types: [python]
        args: [--py38-plus]
        files: ^(pyLIDAR/|tests/)
